# Pandas Dataframe

<img src="https://frenzy86.s3.eu-west-2.amazonaws.com/IFAO/dataframe.png" width="1200">

In [1]:
import numpy as np
import pandas as pd

np.random.seed(667)
r_matrix = np.random.randint(0,101,(4,3))
print("Matrice numpy iniziale")
print(r_matrix)
print("\n\n")
print("Creazione dataframe pandas")
df = pd.DataFrame(data=r_matrix)
print(df)
print("\n\n")
print("aggiunto indici riga")
myindex = ['CA','NY','AZ','TX']
df = pd.DataFrame(index=myindex,data=r_matrix)
print(df)
print("\n\n")
print("aggiunto indici colonna")
mycolumns = ['Jan','Feb','Mar']
df = pd.DataFrame(index=myindex,columns=mycolumns,data=r_matrix)
print(df)
print("\n\n")
print("stampa informazioni generiche")
print(df.info())
print("\n\n")

print("stampa colonna")
print(df['Jan'])
print("\n\n")

print("Converti in lista colonna")
print(df['Jan'].tolist())


Matrice numpy iniziale
[[ 85  15  89]
 [100   3  90]
 [  2  64   0]
 [ 36  99  47]]



Creazione dataframe pandas
     0   1   2
0   85  15  89
1  100   3  90
2    2  64   0
3   36  99  47



aggiunto indici riga
      0   1   2
CA   85  15  89
NY  100   3  90
AZ    2  64   0
TX   36  99  47



aggiunto indici colonna
    Jan  Feb  Mar
CA   85   15   89
NY  100    3   90
AZ    2   64    0
TX   36   99   47



stampa informazioni generiche
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int64
 1   Feb     4 non-null      int64
 2   Mar     4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes
None



stampa colonna
CA     85
NY    100
AZ      2
TX     36
Name: Jan, dtype: int64



Converti in lista colonna
[85, 100, 2, 36]


# secondo esempio

In [2]:
import pandas as pd


data = {'Nome':['Gianni','Enrico','Sergio','Andrea','Marco'],
        'Eta': [23,56,32,None,35],
        'Professione':['cuoco','postino','manager','sbirro','inoccupato']
        }

df1 = pd.DataFrame(data)
print(df1)
print(df1.info())

     Nome   Eta Professione
0  Gianni  23.0       cuoco
1  Enrico  56.0     postino
2  Sergio  32.0     manager
3  Andrea   NaN      sbirro
4   Marco  35.0  inoccupato
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Nome         5 non-null      object 
 1   Eta          4 non-null      float64
 2   Professione  5 non-null      object 
dtypes: float64(1), object(2)
memory usage: 252.0+ bytes
None


## Read external data tables

----
About this DataSet (in case you are interested)

* Description
    * One waiter recorded information about each tip he received over a period of a few months working in one restaurant. He collected several variables:

* Format
    * A data frame with 244 rows and 7 variables

* Details
    * tip in dollars,
    * bill in dollars,
    * sex of the bill payer,
    * whether there were smokers in the party,
    * day of the week,
    * time of day,
    * size of the party.

In all he recorded 244 tips.
    
* Note: I created some additional columns with Fake data, including Name, CC Number, and Payment ID.

----

In [3]:
#!wget https://frenzy86.s3.eu-west-2.amazonaws.com/IFAO/tips_complete.csv -o 04_tips_complete.csv
# local copy of the dataset

In [ ]:
import pandas as pd


url_tips="https://frenzy86.s3.eu-west-2.amazonaws.com/IFAO/tips_complete.csv"
#df = pd.read_csv('tips_complete.csv')
df = pd.read_csv(url_tips)
print("\nHead")
print(df.head())

print("\nVeloce indagine struttura DF\n")
print("Colonne")
print(df.columns)

print("\nIndice righe")
print(df.index)
      
print("\nTail")
print(df.tail())

print("\nInfo")
print(df.info())

print("\nLen")
print(len(df) ) # solo numero di righe

print("\nshape")
print( df.shape ) # forma

print("\nDescrizione trasposta")
print(df.describe().T) #df.describe().transpose()

print("\nSomma-concatena")
print(df.sum()) 


Head
   total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251  

Veloce indagine struttura DF

Colonne
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

Indice righe
RangeIndex(st

## Selection and Indexing

Let's learn how to retrieve information from a DataFrame.

### COLUMNS

We will begin be learning how to extract information based on the columns

In [5]:
import pandas as pd

preview_window=2

url_tips="https://frenzy86.s3.eu-west-2.amazonaws.com/IFAO/tips_complete.csv"
df = pd.read_csv(url_tips)
print("\nViasualizza anteprima testa dataset ------------------------")
print(df.head(preview_window))

print("\nGrab a Single Column ------------------------")
print(df['total_bill'][:preview_window])

print("\nCheck type ------------------------")
print(type(df['total_bill'])) # pandas series == numpy array

print("\nCheck mean ------------------------")
print(df[['tip','total_bill']].mean()) 

print("\nReturn single named column ------------------------")
print(df.total_bill) 

print("\nGrab Multiple Columns ------------------------")
# Note how its a python list of column names! Thus the double brackets.
print(df[['total_bill','tip']][:preview_window])  # è una lista di selezione!!! ref SQL

print("\nCreate new column ------------------------")
df['new'] = 2
print(df.head(preview_window)) 

print("\nOperation by column ------------------------")
df['tip_percentage']=100* df['tip'] / df['total_bill']
df['price_per_person'] = df['total_bill'] / df['size']
print(df.head(preview_window)) 

print("\nAdjust Existing Columns ------------------------")
print("Because pandas is based on numpy, we get awesome capabilities with numpy's universal functions!")
df['price_per_person'] = np.round(df['price_per_person'],2)
print(df.head(preview_window)) 

print("\nRemove Columns ------------------------")
df = df.drop('tip_percentage',axis=1) #  #sovrascrivere!!!!!!!
print(df.head(preview_window)) 

print("\nIndex Basics ------------------------")
print("Before going over the same retrieval tasks for rows, let's build some basic understanding of the pandas DataFrame Index.")
print(df.index[:preview_window]) 
print("\nIndex Payment ID")
df = df.set_index('Payment ID') #sovrascrivere!!!!!!!
print(df.head(preview_window)) 
print("\nIndex tip")
print(df.set_index('tip').head(preview_window))  # does it make sense?
print("\nIndex reset")
df = df.reset_index()
print(df.index[:preview_window]) 


print("\nROWS ------------------------")
print("Let's now explore these same concepts but with Rows.")

print("\nGrab a Single Row")
print(df.iloc[0]) # prende la riga con indice indicato

print("\nName Based")
df = df.set_index('Payment ID')
print(df.loc['Sun2959']) # pesca dall'index


print("\nGrab Multiple Rows ------------------------")
print("\nprime righe")
print(df.iloc[0:4]) #prime 4 righe

print("\nprime per named index")
print(df.loc[['Sun2959','Sun5260']])
print("\nprime per step -2")
print(df.iloc[:,-2:].head(preview_window))
print("\ndrop per named index")
print(df.drop('Sun2959',axis=0).head(preview_window))


print("\nInsert a New Row ------------------------")
print("""Pretty rare to add a single row like this. 
Usually you use pd.concat() to add many rows at once. 
You could use the .append() method with a list of pd.Series() objects, 
but you won't see us do this with realistic real-world data.""")

print("\nprima riga separata")
one_row = df.iloc[0]
print(one_row)
print(type(one_row))
print("\nStampa ultime righe")
print(df.tail(preview_window))

print("\nStampa ultime righe con riga appesa")
# df.append(one_row).tail() # deprecato
df.loc[len(df)] = one_row
print(df.tail(preview_window))


print("\nExtract an array ------------------------")
array_row = df.iloc[0].values
print(array_row[:preview_window])

print("\nExtract a list ------------------------")
print(df['total_bill'].tolist()[:preview_window] )



Viasualizza anteprima testa dataset ------------------------
   total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  

Grab a Single Column ------------------------
0    16.99
1    10.34
Name: total_bill, dtype: float64

Check type ------------------------
<class 'pandas.core.series.Series'>

Check mean ------------------------
tip            2.998279
total_bill    19.785943
dtype: float64

Return single named column ------------------------
0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

Grab Multiple Columns -------------