## 1 Calcolare il valore massimo:

In [1]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
max_value = array.max()
print("Valore massimo:", max_value)

Valore massimo: 8


## 2 Calcolare il valore minimo:

In [2]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
min_value = array.min()
print("Valore minimo:", min_value)

Valore minimo: 1


## 3 Calcolare la somma di tutti gli elementi:

In [3]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
sum_value = array.sum()
print("Somma di tutti gli elementi:", sum_value)

Somma di tutti gli elementi: 26


## 4 Calcolare la media degli elementi:

In [4]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
mean_value = array.mean()
print("Media degli elementi:", mean_value)

Media degli elementi: 4.333333333333333


## 5 Contare il numero totale di elementi:

In [5]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
count_value = array.size
count_value = len(array)
print("Numero totale di elementi:", count_value)

Numero totale di elementi: 6


## 6 Contare il numero di elementi distinti:


In [6]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7, 5, 3])
unique_count=len(set(array))
print("Numero di elementi distinti:", unique_count)

Numero di elementi distinti: 6


## 7 Trova gli indici degli elementi massimi:

In [7]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
max_indices = list(array).index(array.max())
print("Indice dell'elemento massimo:", max_indices)

Indice dell'elemento massimo: 2


## 8 Trova gli indici degli elementi minimi:


In [8]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
min_indices = list(array).index(array.min())
print("Indice dell'elemento minimo:", min_indices)

Indice dell'elemento minimo: 0


## 9 Calcolare la deviazione standard:
$$
σ=\sqrt{{1 \over N}\underset{i=1}{\overset{n}{∑}}(x_i- µ_x)^2}
$$



In [9]:
import numpy as np

array = np.array([1, 5, 8, 3, 2, 7])
std_dev = array.std()
print("Deviazione standard:", std_dev)

Deviazione standard: 2.560381915956203


## 10 Calcolare la varianza:
$$
σ^2={{1 \over N}\underset{i=1}{\overset{n}{∑}}(x_i- µ_x)^2}
$$

In [10]:
import numpy as np

# quanto i valori di un insieme di dati si discostano dalla loro media
array = np.array([1, 5, 8, 3, 2, 7])
variance = (array.std())**2
print("Varianza: ", variance)

Varianza:  6.555555555555556


## 11 Concatenare due array di stringhe:

In [11]:
import numpy as np

array1 = np.array(["hello", "world"])
array2 = np.array(["good", "morning"])

concatenated_array = np.concatenate([array1 , array2], axis=0) # axis 0 single dimension
print("Array concatenato:", concatenated_array)

Array concatenato: ['hello' 'world' 'good' 'morning']


## 12 Trova la lunghezza di ciascuna stringa nell'array:

In [12]:
#vectorize
import numpy as np

array = np.array(["apple", "banana", "kiwi"])
lengths = np.vectorize(len)(array) # funzionale
lengts =  np.char.str_len(array)
print("Lunghezza di ciascuna stringa:", lengths) # [5 6 4]

Lunghezza di ciascuna stringa: [5 6 4]


## 13 Convertire tutte le stringhe in maiuscolo:

In [13]:
#char
import numpy as np

array = np.array(["hello", "world"])
uppercase_array = np.vectorize(str.upper)(array) # pass classfunction
# https://numpy.org/doc/stable/reference/generated/numpy.char.lower.html
print("Stringhe in maiuscolo:", uppercase_array) # ['HELLO' 'WORLD']

Stringhe in maiuscolo: ['HELLO' 'WORLD']


## 14 Contare il numero totale di caratteri in tutto l'array:

In [14]:
import numpy as np

array = np.array(["apple", "banana", "kiwi"])

total_characters = np.char.str_len(array).sum()
print("Numero totale di caratteri:", total_characters) # 15

Numero totale di caratteri: 15


## 15 Trova l'indice della stringa più lunga:

In [15]:
#argmax

import numpy as np
array = np.array(["apple", "banana", "kiwi"])
index_longest_string = array.argmax()
print("Indice della stringa più lunga:", index_longest_string)

Indice della stringa più lunga: 2


## 16 Verifica se ogni stringa inizia con una determinata sottostringa:

In [16]:
#char
import numpy as np

array = np.array(["apple", "banana", "kiwi"])
#starts_with_a = np.strings.startswith(array,'a') # __version__ 2.2
starts_with_a = np.char.startswith(array,'a') # np.__version__ 1.26.4
print("Inizia con 'a':", starts_with_a)

Inizia con 'a': [ True False False]


## 17 Contare il numero di stringhe uniche:

In [17]:
import numpy as np

array = np.array(["apple", "banana", "kiwi", "apple"])
_ , unique_count = np.unique(array, return_counts=True) # both version

print("Numero di stringhe uniche:", len(unique_count) )

Numero di stringhe uniche: 3


## 18 Unire tutte le stringhe in un'unica stringa:

In [18]:
#char
import numpy as np

array = np.array(["hello", "world"])
joined_string = np.char.add(array, " ") # add ' ' at end for each
result = ''.join(joined_string) # not works result = np.char.join("", joined_string)
print("Stringa risultante:", result)

Stringa risultante: hello world 


## 19 Verificare se una determinata sottostringa è presente in ogni stringa:

In [19]:
#list compr
import numpy as np
# https://numpy.org/doc/1.26/reference/generated/numpy.char.find.html
array = np.array(["apple", "banana", "kiwi"])
contains_ki = np.char.find(array, "ki", start=0, end=None)
contains_ki = [True if i==0 else False for i in contains_ki   ]
print("Contiene 'ki':", contains_ki)

Contiene 'ki': [False, False, True]


## 20 Sostituire una sottostringa con un'altra in tutte le stringhe:

In [20]:
#char
import numpy as np

array = np.array(["apple", "banana", "kiwi"])
replaced_array = np.char.replace(array,'a' , 'X')
print("Array con sostituzioni:", replaced_array)

Array con sostituzioni: ['Xpple' 'bXnXnX' 'kiwi']


# 21 impila 2 vettori numpy

In [21]:
import numpy as np

np1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])
np2 = np.array([[1, 0, 3, 1, 5, 6, 4, 4]])

pila = np.column_stack((np1[0], np2[0]))

print("Pila due array compatibili: \n" , pila)

Pila due array compatibili: 
 [[1 1]
 [2 0]
 [3 3]
 [4 1]
 [5 5]
 [6 6]
 [7 4]
 [8 4]]


# 22 Prodotto matriciale

$$
\mathbf{z} = \mathbf{W} \overline{\mathbf{x}} + \overline{\mathbf{b}}
$$

In [22]:
import numpy as np

#weights = np.random.uniform(-0.1, 0.1, (8, 2))  # 3x2 con valori tra -0.1 e 0.1 for a random test
np1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])
np2 = np.array([[1, 0, 3, 1, 5, 6, 4, 4]])

W = np.column_stack((np1[0], np2[0])) # shape (8, 2)

#b = np.random.uniform(-0.1, 0.1, 3)  # 3x1 con valori tra -0.1 e 0.1
b = np.array([-1,-3,-7,10, 20, 30, 40, 50]) # shape (8, 1)
x = np.array([1, 2]) # 2x1

out_l = np.dot(W, x) + b # dot is matricial multiplication built.in

# rank
# [1x2][2x8]+[8]
print("Vettore risultati rank theorem: \n" , out_l)

Vettore risultati rank theorem: 
 [ 2 -1  2 16 35 48 55 66]


# 23 standardizzazione dataset

La formula per trasformare ogni elemento $x$ di un dataset è:
$$
z = \frac{x - \mu}{\sigma}
$$
Dove:
- $x$ = valore originale.
- $\mu$ = media dei dati. $\mu = \frac{1}{n} \sum_{i=1}^n x_i$
- $\sigma$ = deviazione standard dei dati.

Dopo la standardizzazione:
- La media dei dati sarà 0: $\mu' = 0$.
- La deviazione standard sarà 1: $\sigma' = 1$.


In [23]:
import numpy as np

x = np.array([-1,-3,-7,10, 20, 30, 40, 50])

mean = np.mean(x)
std = np.std(x)
z = (x - mean) / std
print("Dataset standardizzato: \n" , z)

Dataset standardizzato: 
 [-0.92691456 -1.02780322 -1.22958054 -0.37202693  0.13241637  0.63685967
  1.14130297  1.64574627]


# 24 Normalizzazione in ℙ

## Softmax
### **Definizione matematica**
Data una sequenza di valori reali $z_1, z_2, \dots, z_n$, la funzione softmax è definita come:

$$
\sigma(z_i) = \frac{e^{z_i}}{\sum_{j=1}^{n} e^{z_j}}
$$

dove:
- $e^{z_i}$ esegue un'esponenziazione sui valori in ingresso, rendendoli tutti positivi.
- Il denominatore normalizza i valori, facendo sì che la somma degli output sia sempre $!$, trasformando il vettore in una distribuzione di probabilità.

### **Proprietà**
1. **Output normalizzato**: La somma degli elementi dell'output è sempre \( 1 \).
2. **Enfatizza i valori maggiori**: L'esponenziale amplifica le differenze tra i valori in ingresso.
3. **Sensibile agli outlier**: I valori più grandi hanno un impatto molto maggiore rispetto a quelli piccoli.

### **Uso nel Machine Learning**
- In **reti neurali** per classificazione multi-classe (ad esempio, nella classificazione di immagini con CNN).
- In **modelli probabilistici**, per interpretare l'output come una distribuzione di probabilità.
- In **reinforcement learning**, per selezionare azioni basate su probabilità.

Hai bisogno di un'implementazione in Python?

In [24]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x)) 
    return exp_x / np.sum(exp_x)

dataset = np.array([-1,-3,-7,10, 20, 30, 40, 50])

normalized = softmax(dataset)
print("Dataset normalizzato softmax: \n" , normalized)

Dataset normalizzato softmax: 
 [7.09515203e-23 9.60224409e-24 1.75871235e-25 4.24816138e-18
 9.35719813e-14 2.06106005e-09 4.53978686e-05 9.99954600e-01]


In [25]:
data = np.array([[1, 2], [3, 4], [5, 6]])
max_val = np.max(np.abs(data))  
data_normalized = data / max_val  
print("Normalized Data:\n", data_normalized)

Normalized Data:
 [[0.16666667 0.33333333]
 [0.5        0.66666667]
 [0.83333333 1.        ]]


# 25 Trasformazioni in ℝ

## Cauchy

### **Analisi della trasformazione**
La funzione implementata:

$$
y = \frac{1}{\pi} \arctan\left(\frac{x - x_0}{\gamma}\right) + 0.5
$$

è la **funzione di ripartizione (CDF) della distribuzione di Cauchy** centrata in $x_0$ (la mediana dei dati) e con un parametro di scala $\gamma$ (qui derivato dall'intervallo interquartile, $IQR / 2$

### **Proprietà**
- Il denominatore normalizza rispetto a $\gamma$, che controlla la dispersione dei dati.
- Il risultato è sempre tra $(0,1)$, rendendolo simile a una trasformazione sigmoide.

In [26]:
import numpy as np

def cauchy(data):
    x0 = np.median(data)
    IQR = np.percentile(data, 75) - np.percentile(data, 25)
    gamma = IQR / 2
    y = (1 / np.pi) * np.arctan((data - x0) / gamma) + 0.5
    return y

dataset = np.array([-1,-3,-7,10, 20, 30, 40, 50])

normalized = cauchy(dataset)
print("Dataset trasformato Cauchy: \n" , normalized)

Dataset trasformato Cauchy: 
 [0.2596428  0.24090791 0.20941245 0.408947   0.591053   0.73013148
 0.80991277 0.85607496]


## Relu
$$
ReLU(x)=max⁡(0,x)
$$

In [27]:
def relu(x):
    return np.maximum(0, x)  # ReLU: max(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)  # derivata 1 se x > 0, altrimenti 0

dataset = np.array([-1,-3,-7,10, 20, 30, 40, 50])
print("ReLU(x):\n", relu(dataset))
print("ReLU Derivative(x):\n", relu_derivative(dataset))

ReLU(x):
 [ 0  0  0 10 20 30 40 50]
ReLU Derivative(x):
 [0. 0. 0. 1. 1. 1. 1. 1.]


# 26 Loss Function

## Mean Squared Error
$$
\text{MSE} = \frac{1}{n} \sum_{i=1}^n (y_{{t}}^{(i)} - y_{{t-1}}^{(i)})^2
$$

In [28]:
y_t = np.array([1, 2, 3])
y_t_1 = np.array([1.1, 1.9, 3.2])
mse = np.mean((y_t - y_t_1) ** 2)  # as is
print("MSE:", mse)

MSE: 0.020000000000000035
